export const appRouteConst = {
  root: "",
  home: "home",
  add: "add",
  play: "play",
  terms: "terms",
  license: "license",
  account: "account",
  register: "register",
  login: "login",
  forgot: "forgot",
  profile: "profile",
  registerRel: "account/register",
  loginRel: "account/login",
  forgotRel: "account/forgot",
  profileRel: "account/profile",
  homeAbs: "/home",
  addAbs: "/add",
  playAbs: "/play",
  termsAbs: "/terms",
  licenseAbs: "/license"
};
