export const appRoute = {
  root: "",
  home: "home",
  add: "add",
  play: "play",
  terms: "terms",
  license: "license",
  account: "account",
  register: "register",
  login: "login",
  forgot: "forgot",
  profile: "profile",
  registerAbs: "/account/register",
  loginAbs: "/account/login",
  forgotAbs: "/account/forgot",
  profileAbs: "/account/profile",
  homeAbs: "/home",
  addAbs: "/add",
  playAbs: "/play",
  termsAbs: "/terms",
  licenseAbs: "/license"
};
