export const pathConst = {
  root: "",
  home: "home",
  add: "add",
  play: "play",
  terms: "terms",
  license: "license",
  user: "user",
  register: "register",
  login: "login",
  account: "account",
  registerRel: "user/register",
  loginRel: "user/login",
  accountRel: "user/account",
  homeAbs: "/home",
  addAbs: "/add",
  playAbs: "/play",
  termsAbs: "/terms",
  licenseAbs: "/license",
};
